# Generated by Django 4.1.2 on 2024-01-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_car_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_Name',
            new_name='car_name',
        ),
    ]
