# Generated by Django 3.1.1 on 2024-02-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20240206_2320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
