# Generated by Django 3.1.1 on 2024-02-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student_user',
        ),
    ]
