# Generated by Django 3.1.1 on 2024-02-06 18:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0011_auto_20240206_2353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_user',
            new_name='Student',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
