# Generated by Django 4.1.2 on 2024-02-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='phone',
        ),
    ]
