# Generated by Django 3.1.1 on 2024-02-13 17:14

from django.db import migrations, models
import djongo.models.fields
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', djongo.models.fields.EmbeddedField(model_container=student.models.Blog)),
                ('headline', models.CharField(max_length=255)),
            ],
        ),
    ]
